CREATE TABLE indoor_users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    role VARCHAR(50) DEFAULT 'indoor_user',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
